package com.gameotaku.app.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nativeGameDaoConfig;
    private final DaoConfig webGameDaoConfig;
    private final DaoConfig downloadGameDaoConfig;
    private final DaoConfig myGameDaoConfig;

    private final NativeGameDao nativeGameDao;
    private final WebGameDao webGameDao;
    private final DownloadGameDao downloadGameDao;
    private final MyGameDao myGameDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nativeGameDaoConfig = daoConfigMap.get(NativeGameDao.class).clone();
        nativeGameDaoConfig.initIdentityScope(type);

        webGameDaoConfig = daoConfigMap.get(WebGameDao.class).clone();
        webGameDaoConfig.initIdentityScope(type);

        downloadGameDaoConfig = daoConfigMap.get(DownloadGameDao.class).clone();
        downloadGameDaoConfig.initIdentityScope(type);

        myGameDaoConfig = daoConfigMap.get(MyGameDao.class).clone();
        myGameDaoConfig.initIdentityScope(type);

        nativeGameDao = new NativeGameDao(nativeGameDaoConfig, this);
        webGameDao = new WebGameDao(webGameDaoConfig, this);
        downloadGameDao = new DownloadGameDao(downloadGameDaoConfig, this);
        myGameDao = new MyGameDao(myGameDaoConfig, this);

        registerDao(NativeGame.class, nativeGameDao);
        registerDao(WebGame.class, webGameDao);
        registerDao(DownloadGame.class, downloadGameDao);
        registerDao(MyGame.class, myGameDao);
    }

    public void clear() {
        nativeGameDaoConfig.getIdentityScope().clear();
        webGameDaoConfig.getIdentityScope().clear();
        downloadGameDaoConfig.getIdentityScope().clear();
        myGameDaoConfig.getIdentityScope().clear();
    }

    public NativeGameDao getNativeGameDao() {
        return nativeGameDao;
    }

    public WebGameDao getWebGameDao() {
        return webGameDao;
    }

    public DownloadGameDao getDownloadGameDao() {
        return downloadGameDao;
    }

    public MyGameDao getMyGameDao() {
        return myGameDao;
    }

}
