package com.gameotaku.app.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table DOWNLOAD_GAME.
 */
public class DownloadGame {

    private Long download_id;
    private long item_id;
    private int type;
    private String request_url;
    private String temp_name;
    private String apk_name;
    private Integer progress;
    private int status;
    /**
     * Not-null value.
     */
    private String package_name;
    private Long total_size;

    public DownloadGame() {
    }

    public DownloadGame(Long download_id) {
        this.download_id = download_id;
    }

    public DownloadGame(Long download_id, long item_id, int type, String request_url, String temp_name, String apk_name, Integer progress, int status, String package_name, Long total_size) {
        this.download_id = download_id;
        this.item_id = item_id;
        this.type = type;
        this.request_url = request_url;
        this.temp_name = temp_name;
        this.apk_name = apk_name;
        this.progress = progress;
        this.status = status;
        this.package_name = package_name;
        this.total_size = total_size;
    }

    public Long getDownload_id() {
        return download_id;
    }

    public void setDownload_id(Long download_id) {
        this.download_id = download_id;
    }

    public long getItem_id() {
        return item_id;
    }

    public void setItem_id(long item_id) {
        this.item_id = item_id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getRequest_url() {
        return request_url;
    }

    public void setRequest_url(String request_url) {
        this.request_url = request_url;
    }

    public String getTemp_name() {
        return temp_name;
    }

    public void setTemp_name(String temp_name) {
        this.temp_name = temp_name;
    }

    public String getApk_name() {
        return apk_name;
    }

    public void setApk_name(String apk_name) {
        this.apk_name = apk_name;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * Not-null value.
     */
    public String getPackage_name() {
        return package_name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setPackage_name(String package_name) {
        this.package_name = package_name;
    }

    public Long getTotal_size() {
        return total_size;
    }

    public void setTotal_size(Long total_size) {
        this.total_size = total_size;
    }

}
