package com.gameotaku.app.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table MY_GAME.
 */
public class MyGame {

    private Long local_id;
    private long item_id;
    private int type;
    /**
     * Not-null value.
     */
    private String package_name;
    private String version_name;
    private Integer version_code;
    private Integer play_count;
    private Integer more_count;
    private Integer status;
    private Long last_play_time;
    private long create_time;

    public MyGame() {
    }

    public MyGame(Long local_id) {
        this.local_id = local_id;
    }

    public MyGame(Long local_id, long item_id, int type, String package_name, String version_name, Integer version_code, Integer play_count, Integer more_count, Integer status, Long last_play_time, long create_time) {
        this.local_id = local_id;
        this.item_id = item_id;
        this.type = type;
        this.package_name = package_name;
        this.version_name = version_name;
        this.version_code = version_code;
        this.play_count = play_count;
        this.more_count = more_count;
        this.status = status;
        this.last_play_time = last_play_time;
        this.create_time = create_time;
    }

    public Long getLocal_id() {
        return local_id;
    }

    public void setLocal_id(Long local_id) {
        this.local_id = local_id;
    }

    public long getItem_id() {
        return item_id;
    }

    public void setItem_id(long item_id) {
        this.item_id = item_id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /**
     * Not-null value.
     */
    public String getPackage_name() {
        return package_name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setPackage_name(String package_name) {
        this.package_name = package_name;
    }

    public String getVersion_name() {
        return version_name;
    }

    public void setVersion_name(String version_name) {
        this.version_name = version_name;
    }

    public Integer getVersion_code() {
        return version_code;
    }

    public void setVersion_code(Integer version_code) {
        this.version_code = version_code;
    }

    public Integer getPlay_count() {
        return play_count;
    }

    public void setPlay_count(Integer play_count) {
        this.play_count = play_count;
    }

    public Integer getMore_count() {
        return more_count;
    }

    public void setMore_count(Integer more_count) {
        this.more_count = more_count;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getLast_play_time() {
        return last_play_time;
    }

    public void setLast_play_time(Long last_play_time) {
        this.last_play_time = last_play_time;
    }

    public long getCreate_time() {
        return create_time;
    }

    public void setCreate_time(long create_time) {
        this.create_time = create_time;
    }

}
