package com.gameotaku.app.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table WEB_GAME.
 */
public class WebGame {

    private Long local_id;
    private long item_id;
    /**
     * Not-null value.
     */
    private String request_url;
    /**
     * Not-null value.
     */
    private String name;
    private String icon;
    private Long size;
    private String language;
    private String type;
    private String desc;
    private Integer charge_type;
    private Integer charge_fee;
    private Boolean orientation;
    private Long create_time;
    private Long update_time;
    private String version_name;
    private Integer version_code;
    private Integer player_count;
    private Integer heat;
    private Integer rate;
    private Integer status;
    private Long author_id;
    private Boolean author_type;
    private String author_name;
    private String ext_url;

    public WebGame() {
    }

    public WebGame(Long local_id) {
        this.local_id = local_id;
    }

    public WebGame(Long local_id, long item_id, String request_url, String name, String icon, Long size, String language, String type, String desc, Integer charge_type, Integer charge_fee, Boolean orientation, Long create_time, Long update_time, String version_name, Integer version_code, Integer player_count, Integer heat, Integer rate, Integer status, Long author_id, Boolean author_type, String author_name, String ext_url) {
        this.local_id = local_id;
        this.item_id = item_id;
        this.request_url = request_url;
        this.name = name;
        this.icon = icon;
        this.size = size;
        this.language = language;
        this.type = type;
        this.desc = desc;
        this.charge_type = charge_type;
        this.charge_fee = charge_fee;
        this.orientation = orientation;
        this.create_time = create_time;
        this.update_time = update_time;
        this.version_name = version_name;
        this.version_code = version_code;
        this.player_count = player_count;
        this.heat = heat;
        this.rate = rate;
        this.status = status;
        this.author_id = author_id;
        this.author_type = author_type;
        this.author_name = author_name;
        this.ext_url = ext_url;
    }

    public Long getLocal_id() {
        return local_id;
    }

    public void setLocal_id(Long local_id) {
        this.local_id = local_id;
    }

    public long getItem_id() {
        return item_id;
    }

    public void setItem_id(long item_id) {
        this.item_id = item_id;
    }

    /**
     * Not-null value.
     */
    public String getRequest_url() {
        return request_url;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setRequest_url(String request_url) {
        this.request_url = request_url;
    }

    /**
     * Not-null value.
     */
    public String getName() {
        return name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(String name) {
        this.name = name;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getCharge_type() {
        return charge_type;
    }

    public void setCharge_type(Integer charge_type) {
        this.charge_type = charge_type;
    }

    public Integer getCharge_fee() {
        return charge_fee;
    }

    public void setCharge_fee(Integer charge_fee) {
        this.charge_fee = charge_fee;
    }

    public Boolean getOrientation() {
        return orientation;
    }

    public void setOrientation(Boolean orientation) {
        this.orientation = orientation;
    }

    public Long getCreate_time() {
        return create_time;
    }

    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    public Long getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }

    public String getVersion_name() {
        return version_name;
    }

    public void setVersion_name(String version_name) {
        this.version_name = version_name;
    }

    public Integer getVersion_code() {
        return version_code;
    }

    public void setVersion_code(Integer version_code) {
        this.version_code = version_code;
    }

    public Integer getPlayer_count() {
        return player_count;
    }

    public void setPlayer_count(Integer player_count) {
        this.player_count = player_count;
    }

    public Integer getHeat() {
        return heat;
    }

    public void setHeat(Integer heat) {
        this.heat = heat;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getAuthor_id() {
        return author_id;
    }

    public void setAuthor_id(Long author_id) {
        this.author_id = author_id;
    }

    public Boolean getAuthor_type() {
        return author_type;
    }

    public void setAuthor_type(Boolean author_type) {
        this.author_type = author_type;
    }

    public String getAuthor_name() {
        return author_name;
    }

    public void setAuthor_name(String author_name) {
        this.author_name = author_name;
    }

    public String getExt_url() {
        return ext_url;
    }

    public void setExt_url(String ext_url) {
        this.ext_url = ext_url;
    }

}
